name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: tanjiyaJuthi
          outputs: dist/snake.svg dist/snake-dark.svg

      - name: Push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate snake animation"
          branch: output
          file_pattern: dist/*.svg